server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/labvaccinebd
    username: postgres
    password: 132724
  jpa:
    hibernate:
      ddl-auto: update
